name: Build and upload
on:
    push:
        branches: [ main ]
jobs:
    build-site:
        name: Build and upload
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v1
          with:
            node-version: '14'
        - name: Install Dependencies
          working-directory: src
          run: npm install
        - name: Build and export
          working-directory: src
          run: npm run export
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Upload files to S3 with AWS CLI
          run: |
            aws s3 sync src/out/ s3://${{ secrets.S3_BUCKET }} --delete 
